baseURL = 'https://emanueles.github.io/'
languageCode = 'en-us'
languageName = "English"

# Custom theme provided by https://github.com/dillonzq/LoveIt
theme = "LoveIt"

title = 'Emanuele Santos'

# default amount of posts in each pages
paginate = 12
# google analytics code [UA-XXXXXXXX-X]
googleAnalytics = ""

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true

# ignore some build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# Author config
[author]
  name = "Emanuele Santos"
  email = "emanuele@dc.ufc.br"
  link = ""

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "publications"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Publications"
    url = "/publications/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "research"
    pre = ""
    post = ""
    name = "Research"
    url = "/projs/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "teaching"
    pre = ""
    post = ""
    name = "Teaching"
    url = "/teaching"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "talks"
    pre = ""
    post = ""
    name = "Talks"
    url = "/talks"
    title = ""
  [[menu.main]]
    weight = 5
    identifier = "students"
    pre = ""
    post = ""
    name = "Students"
    url = "/students"
    title = ""
  [[menu.main]]
    weight = 6
    identifier = "blog"
    pre = ""
    post = ""
    name = "Blog"
    url = "/blog"
    title = ""
  [[menu.main]]
    weight = 7
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about"
    title = ""

[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = ""
  # LoveIt NEW | 0.1.1 which hash function used for SRI, when empty, no SRI is used
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # LoveIt NEW | 0.2.0 date format
  dateFormat = "2006-01-02"
  # website title for Open Graph and Twitter Cards
  title = "Emanuele Santos"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "Emanuele's website"
  # website images for Open Graph and Twitter Cards
  images = ["/images/profile.jpg"]
  
  # Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "/images/logo.png"
      # title name
      name = "Emanuele Santos"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false

  # Footer config
  [params.footer]
    enable = true
    # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
    custom = ''
    # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = true
    # LoveIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # LoveIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2020

  # LoveIt NEW | 0.2.0 Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # LoveIt NEW | 0.2.0 List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # LoveIt NEW | 0.2.0 App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Emanuele Santos"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"
  # LoveIt NEW | 0.2.0 Search config
  [params.search]
    enable = true
    # type of search engine ["lunr", "algolia"]
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # LoveIt NEW | 0.2.1 max number of results length
    maxResultLength = 10
    # LoveIt NEW | 0.2.3 snippet length of the result
    snippetLength = 30
    # LoveIt NEW | 0.2.1 HTML tag name of the highlight part in results
    highlightTag = "em"
    # LoveIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  # Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/profile.jpg"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "Emanuele Santos"
      # subtitle shown in home page (HTML format is supported)
      subtitle = "Computer Scientist & Visualization Researcher"
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
      # Emanuele's changed this to show a welcome message
      welcome = '<p>Hi! I am Emanuele. I am an associate professor in the <a href="http://portal.dc.ufc.br/">Department of Computer Science</a> at the <a href="http://www.ufc.br">Universidade Federal do Ceará</a>, in Brazil. My research interests include data visualization and data science.</p><p> Feel free to learn more <a href="/about">about me</a> and see my <a href="/publications">publications</a>. You can contact me using the social icons at the top of this page.</p>'
    # Home page posts
    [params.home.posts]
      enable = false
      # special amount of posts in each home posts page
      paginate = 6
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  # Social config about the author
  [params.social]
    GitHub = "emanueles"
    Linkedin = ""
    Twitter = "emanueles"
    Instagram = "prof.manu.ufc"
    Facebook = ""
    Telegram = "emanuelesantos"
    Medium = ""
    Gitlab = ""
    Youtubehandle = "@emanueles"
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Mastodon = ""
    Thingiverse = ""
    Devto = ""
    Gitea = ""
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    Discord = ""
    DiscordInvite = ""
    Lichess = ""
    ORCID = ""
    Pleroma = ""
    Kaggle = ""
    MediaWiki= ""
    Plume = ""
    HackTheBox = ""
    RootMe= ""
    Lattes= "3334643879272311"
    Phone = ""
    Email = "emanuele@dc.ufc.br"
    RSS = false # LoveIt NEW | 0.2.0

# {{< version 0.2.0 >}} Analytics config
  [params.analytics]
    enable = false
    # Google Analytics
    [params.analytics.google]
      id = "G-RCVSKCG9EC"
      # whether to anonymize IP
      anonymizeIP = true

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false